### ISSUE TITLE
Set `log` features on `tracing` as well

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#199]
Per `Cargo.toml`, we should only see logs for release builds that are at least `warn`, i.e. only `warn` and `error`.
```toml
[dependencies.log]
version = "*"
# Disable low-severity logs at compile time for performance.
features = ["max_level_debug", "release_max_level_warn"]
```
see the relevant documentation:
![image](https://github.com/user-attachments/assets/0dec1857-02a2-4f36-ab28-243ed594c7ed)

However, opening the console in https://the-bevy-flock.itch.io/bevy-quickstart shows that we receive `info` logs:
![image](https://github.com/user-attachments/assets/83a0d5a8-130e-4cf3-bf93-d782800bb285)
